src/app/back-end/booking/urls.py
from django.urls import path

from . import views

app_name = 'booking'
urlpatterns = [
    path('<str:username>/book/', views.booking_view, name='client_book'),
    path('<str:username>/filter/', views.filter_view, name='client_book_filter'),
    path('<str:username>/bookings/', views.booking_list, name='booking_list'),
    path('<str:username>/bookings/<booking_id>/pdf/', views.booking_pdf, name='booking_pdf'),
    path(
        '<str:username>/bookings/<booking_id>/delete', views.delete_booking, name='delete_booking'
    ),
    path('completed/<int:booking_id>/', views.payment_success, name='payment_completed'),
    path('cancelled/<int:booking_id>/', views.payment_cancel, name='payment_cancelled'),
]

src/app/back-end/hotel/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
]

src/app/back-end/jhoola/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from users import views as user_views

from .router import router

urlpatterns = [
    path('login/', user_views.user_login, name='user_login'),
    path('', include('django.contrib.auth.urls')),
    path('', include('hotel.urls')),
    path('', include('users.urls')),
    path('', include('booking.urls')),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/app/back-end/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('manager/bookings/', views.bookings_manager_view, name='manager_bookings'),
    path('manager/products/', views.products_manager_view, name='manager_products'),
    path('manager/', views.manager_dashboard, name='manager_dashboard'),
    path('manager/users/', views.users_manager_view, name='manager_users'),
    path('manager/products/add', views.products_add_manager_view, name='manager_products_add'),
    path('manager/users/add', views.users_add_manager_view, name='manager_users_add'),
    path(
        'manager/users/<username>/edit/', views.users_edit_manager_view, name='manager_users_edit'
    ),
    path(
        'manager/products/<product_id>/edit/',
        views.products_edit_manager_view,
        name='manager_products_edit',
    ),
    path(
        'manager/users/<username>/delete/',
        views.users_delete_manager_view,
        name='manager_users_delete',
    ),
    path(
        'manager/products/<product_id>/delete/',
        views.products_delete_manager_view,
        name='manager_products_delete',
    ),
    path(
        'manager/bookings/<booking_id>/delete/',
        views.bookings_delete_manager_view,
        name='manager_bookings_delete',
    ),
    path(
        'manager/search/<path:query>',
        views.search_manager_view,
        name='manager_search',
    ),
    path(
        'manager/check_reservation/',
        views.check_booking_manager_view,
        name='manager_check_booking',
    ),
]

src/app/back-end/booking/models.py
from django.db import models

from product.models import Product
from users.models import Client


class PaidManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(paid=True)


class Booking(models.Model):
    class TimeSlots(models.TextChoices):
        MORNING = 'MOR', 'Morning'
        AFTERNOON = 'AFT', 'Afternoon'
        ALL_DAY = 'ALL', 'All Day'

        @classmethod
        def get_display_with_hours(cls, slot, morning_hours, afternoon_hours):
            slot_display = dict(cls.choices)[slot]
            if slot == cls.MORNING:
                return f'{slot_display} ({morning_hours})'
            if slot == cls.AFTERNOON:
                return f'{slot_display} ({afternoon_hours})'
            else:
                return slot_display

    user = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='bookings')
    products = models.ManyToManyField(Product)
    timestamp = models.DateTimeField(auto_now_add=True, editable=False)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    duration = models.CharField(max_length=3, choices=TimeSlots.choices)
    date = models.DateField()
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['date']

    def __str__(self):
        return f'{self.id}'

    @property
    def get_duration_display(self):
        if self.duration == self.TimeSlots.MORNING:
            return f'Morning ({self.user.hotel.opening_morning_hours})'
        elif self.duration == self.TimeSlots.AFTERNOON:
            return f'Afternoon ({self.user.hotel.opening_afternoon_hours})'
        else:
            return 'All Day'

src/app/back-end/booking/forms.py
from django import forms
from django.utils import timezone

from product.models import Product

from .models import Booking
from hotel.models import Hotel  


class BookingFilterForm(forms.Form):
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    duration = forms.ChoiceField()

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.fields['duration'].choices = self.get_duration_choices(self.user.hotel)
        self.fields['duration'].initial = Booking.TimeSlots.ALL_DAY

    def clean_date(self):
        date = self.cleaned_data.get('date')
        actual_date = timezone.now().date()
        max_date = actual_date + timezone.timedelta(days=7)

        if actual_date <= date > max_date:
            raise forms.ValidationError('You can only reserve up to one week from today.')
        if date < actual_date:
            raise forms.ValidationError('You cannot reserve for past dates.')
        return date

    def get_duration_choices(self,hotel):
        hotel = Hotel.objects.get(id=hotel.id)
        morning_hours = hotel.opening_morning_hours
        afternoon_hours = hotel.opening_afternoon_hours

        duration_choices = [
            (choice[0], Booking.TimeSlots.get_display_with_hours(choice[0], morning_hours, afternoon_hours)) 
            for choice in Booking.TimeSlots.choices
        ]
        return duration_choices


class BookingForm(forms.ModelForm):
    products = forms.ModelMultipleChoiceField(
        queryset=Product.objects.all(), widget=forms.CheckboxSelectMultiple, required=False
    )

    class Meta:
        model = Booking
        fields = ['products']

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.fields['products'].queryset = Product.objects.filter(hotel=self.user.hotel)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.user = self.user
        if commit:
            instance.save()
        return instance

    def clean_products(self):
        products = self.cleaned_data.get('products')
        user = self.user
        max_products = user.num_guest

        if not products:
            raise forms.ValidationError('You have to choose at least one product')

        if len(products) > max_products:
            raise forms.ValidationError(
                f'You can only reserve a maximum of {max_products} products per time slot.'
            )

        return products

src/app/back-end/booking/api/views.py
from rest_framework import viewsets
from rest_framework.permissions import IsAdminUser

from booking.models import Booking
from users.api.permissions import AdminSiteAccess
from users.models import Client

from .serializers import BookingSerializer


class BookingViewSet(viewsets.ModelViewSet):

    serializer_class = BookingSerializer
    permission_classes = [IsAdminUser | AdminSiteAccess]

    def get_queryset(self):
        bookings = Booking.objects.all()
        if self.request.user.is_staff:
            return bookings
        client = Client.objects.get(user=self.request.user)
        return bookings.filter(user__hotel=client.hotel)

src/app/back-end/booking/views.py
from base64 import b64encode
from datetime import datetime
from io import BytesIO

import weasyprint
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Count
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from qrcode import make

from booking.forms import BookingFilterForm, BookingForm
from product.models import Product
from users.decorators import client_required
from users.models import Client

from .models import Booking
from .tasks import booking_created


@login_required
@client_required
def booking_list(request, username):
    client = get_object_or_404(Client, user=request.user)
    actual_datetime = timezone.now().date()
    bookings = Booking.objects.filter(user=client, date__gte=actual_datetime, paid=True)
    paginator = Paginator(bookings, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(
        request, 'users/pages/bookings.html', {'page_obj': page_obj, 'section': 'My Bookings'}
    )


@client_required
@login_required
def booking_pdf(request, username, booking_id):
    booking = get_object_or_404(Booking, id=booking_id, user__user=request.user)
    selected_hotel = request.session.get('hotel_session_name')
    get_params = f'?booking_id={booking.id}&client_id={request.user.id}&hotel={selected_hotel}'
    path_qr = request.build_absolute_uri(f"{reverse('users:manager_check_booking')}{get_params}")
    qr_rend = BytesIO()
    img = make(path_qr)
    img.save(qr_rend, 'PNG')
    qr_url = f'data:image/png/;base64,{b64encode(qr_rend.getvalue()).decode("ascii")}'
    html = render_to_string('users/pages/pdf.html', {'booking': booking, 'qr': qr_url})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=transaction_{booking_id}.pdf'
    weasyprint.HTML(string=html, base_url=request.build_absolute_uri()).write_pdf(response)
    return response


@login_required
@client_required
def booking_view(request, username):
    date, duration, client, occupied_products, max_products = get_context_data(request, username)
    formatted_date = datetime.strptime(date, '%Y-%m-%d').strftime('%d/%m/%Y')
    formatted_duration = dict(Booking.TimeSlots.choices)[duration]
    if request.method == 'POST':
        form = BookingForm(user=client, data=request.POST)
        if form.is_valid():
            booking = form.save(commit=False)
            products = form.cleaned_data['products']
            if len(products) > max_products:
                messages.error(request, 'You have already reserved all possible hammocks for your account.')
                return redirect('booking:client_book', client)

            if any(
                [
                    product.status
                    for product in products
                    if product.status == Product.Status.OCCUPIED
                ]
            ):
                messages.error(request, 'The selected hammocks are being reserved by another user')
                return redirect('booking:client_book', client)

            total_price = sum(product.price for product in products)
            booking.user = client
            booking.price = total_price
            booking.date = date
            booking.duration = duration
            booking.save()
            form.save_m2m()
            for product in booking.products.all():
                product.status = Product.Status.OCCUPIED
                product.save()
            line_items = [
                {
                    'price_data': {
                        'currency': 'eur',
                        'product_data': {
                            'name': 'Booking',
                        },
                        'unit_amount': int(total_price * 100),
                    },
                    'quantity': 1,
                }
            ]
            metadata = {'booking_id': booking.id}
            success_url = request.build_absolute_uri(
                reverse('booking:payment_completed', kwargs={'booking_id': booking.id})
            )
            cancel_url = request.build_absolute_uri(
                reverse('booking:payment_cancelled', kwargs={'booking_id': booking.id})
            )

            task = booking_created.delay(
                success_url,
                cancel_url,
                metadata,
                line_items,
            )
            url = task.get()
            return redirect(url)
        else:
            for errors in form.errors.values():
                for error in errors:
                    messages.error(request, error)
    else:
        form = BookingForm(user=client)
        products = form.fields['products'].queryset
        for product in products.all():
            product.status = Product.Status.FREE
            product.save()
    return render(
        request,
        'users/pages/book.html',
        {
            'form': form,
            'section': 'Reserve',
            'occupied_products': occupied_products,
            'duration': formatted_duration,
            'date': formatted_date,
        },
    )


@client_required
@login_required
def payment_success(request, booking_id):
    booking = get_object_or_404(Booking, id=booking_id)
    booking.paid = True
    for product in booking.products.all():
        product.status = Product.Status.FREE
        product.save()
    booking.save()

    messages.success(request, 'Your hammocks have been properly reserved')
    return redirect('booking:booking_list', booking.user)


@client_required
@login_required
def payment_cancel(request, booking_id):
    booking = get_object_or_404(Booking, id=booking_id)
    for product in booking.products.all():
        product.status = Product.Status.FREE
        product.save()
    booking.delete()

    messages.error(request, 'There has been an error with your reservation')
    return redirect('booking:booking_list', booking.user)


@login_required
@client_required
def delete_booking(request, username, booking_id):
    client = get_object_or_404(Client, user=request.user)
    booking = get_object_or_404(Booking, id=booking_id, user=client)
    booking.delete()
    messages.success(request, f'Reservation {booking_id} has been succesfully deleted')
    return redirect('booking:booking_list', username=username)


@login_required
@client_required
def filter_view(request, username):
    client = get_object_or_404(Client, user=request.user)
    if request.method == 'POST':
        form = BookingFilterForm(user=client, data=request.POST)
        if form.is_valid():
            request.session['date'] = form.cleaned_data['date'].strftime('%Y-%m-%d')
            request.session['duration'] = form.cleaned_data['duration']
            return redirect('booking:client_book', username=username)
        else:
            for errors in form.errors.values():
                for error in errors:
                    messages.error(request, error)
    else:
        form = BookingFilterForm(user=client)
    return render(request, 'users/pages/filter.html', {'section': 'Reserve', 'form': form})


def get_context_data(request, username):
    date = request.session.get('date')
    duration = request.session.get('duration')
    client = get_object_or_404(Client, user=request.user)
    user_bookings = Booking.objects.filter(date=date, paid=True, user=client)
    total_products = (
        user_bookings.aggregate(total_products=Count('products'))['total_products'] or 0
    )
    max_products = client.num_guest - total_products
    all_date_bookings = Booking.objects.filter(paid=True, date=date)
    occupied_products = []
    match duration:
        case Booking.TimeSlots.AFTERNOON | Booking.TimeSlots.MORNING:
            bookings = all_date_bookings.filter(duration=duration)
            occupied_products.extend(
                [product.id for booking in bookings for product in booking.products.all()]
            )
            all_day_bookings = all_date_bookings.filter(duration=Booking.TimeSlots.ALL_DAY)
            for booking in all_day_bookings:
                occupied_products.extend([product.id for product in booking.products.all()])
        case Booking.TimeSlots.ALL_DAY:
            for booking in all_date_bookings:
                occupied_products.extend([product.id for product in booking.products.all()])

    return (date, duration, client, occupied_products, max_products)

src/app/back-end/users/api/views.py
from rest_framework import viewsets
from rest_framework.permissions import IsAdminUser

from users.models import Client

from .permissions import AdminSiteAccess
from .serializers import ClientSerializer


class ClientViewSet(viewsets.ModelViewSet):
    serializer_class = ClientSerializer
    permission_classes = [IsAdminUser | AdminSiteAccess]

    def get_queryset(self):

        if self.request.user.is_staff:
            return Client.objects.all()
        client = Client.objects.get(user=self.request.user)
        return Client.objects.filter(hotel=client.hotel)

src/app/back-end/users/templates/users/pages/bookings.html
{% extends "users/dashboard.html" %}

{% block title %}My reservations{% endblock %}
{% block content %}

<div class="container">

  {% block messages %}
    {% include "users/messages/message.html" %}
  {% endblock messages %}

  {% if page_obj %}
  <div class="row mt-4 text-white">
    <h2>Happy Holidays, {{ user.first_name }}!! </h2>
  </div>
  <div class="row">
    {% for booking in page_obj %}
    <div class="col-12 mt-4">
      <div class="card">
        <div class="card-header bg-dark text-white">
          Reservation ID: {{ booking.id }}
        </div>
        <div class="card-body">
          <div class="booking-info d-flex flex-row justify-content-between">
            <h5 class="card-title col-md-3 col-6 order-0 mb-3">{{ booking.products.first }} x {{ booking.products.count }}</h5>
            <p class="card-text col-md-3 col-6 order-lg-2 order-3 d-md-block d-none">Date: {{ booking.date|date:"l, d/m/Y" }}</p>
            <p class="card-text col-md-3 col-6 order-lg-1 order-2 d-md-block d-none">Reserved time: {{ booking.get_duration_display }}</p>
            <h5 class="card-title col-md-1 col-6 order-md-3 order-1 text-end">{{ booking.price }}€</h5>
          </div>
          <div class="card-sm-body d-md-none d-block mb-3">
            <p class="card-text ">Date: {{ booking.date|date:"l, d/m/Y" }}</p>
            <p class="card-text ">Reserved time: {{ booking.get_duration_display }}</p>            
          </div>
          <div>
            <p> Your hammocks:
              {% for product in booking.products.all %}
              {{ product.id }}{% if not forloop.last %},{% endif %}
              {% endfor %}
            </p>
          </div>
          <div class="row user-actions">
            <div class="col-6">
              <a href="{% url "booking:booking_pdf" user.username booking.id %}" class="btn btn-dark">Download PDF</a>
            </div>
            <div class="col-6 d-flex justify-content-end">
              <a href="#" class="delete-btn btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal{{ booking.id }}">Delete reservation</a>
            </div>
          </div>
        </div>
      </div>
      {% comment %} Modal {% endcomment %}
      <div class="modal fade" id="deleteModal{{ booking.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Delete reservation ID: {{ booking.id }}</h1>
              <button type="button" class="btn-close bg-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Are you sure you want to delete this reservation?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
              <a href="{% url 'booking:delete_booking' user.username booking.id %}" class="delete-btn btn btn-danger">Confirm</a>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}

    {% block paginator %}
      {% include "users/paginator.html" %}
    {% endblock paginator %}

  </div>
  {% else %}
  <div class="row">
    <div class="col-12 d-flex justify-content-center align-items-end p-5 text-white">
      <h3>Looks like you haven't made any reservations yet, start your break <a href="{% url 'booking:client_book_filter' user.username %}" class="link-light link-offset-2 link-underline-opacity-100 link-opacity-75-hover link-underline-opacity-75-hover" id="no-bookings-yet">here</a></h3>
    </div>
  </div>
  {% endif %}
</div>

{% endblock content %}

src/app/back-end/users/templates/users/pages/filter.html
{% extends "users/dashboard.html" %}

{% block title %}Book your hammocks{% endblock title %}
{% block content %}

    <div class="container">

        {% block messages %}
            {% include "users/messages/message.html" %}
        {% endblock messages %}

        <div class="row mt-4 text-white text-center d-flex flex-row">
            <a href="javascript:history.back()" class="d-flex align-items-center pt-2 pb-2 text-end text-decoration-none">
                <span class="material-symbols-outlined m-0 text-end text-white">
                    arrow_back
                </span>
            </a>
            <h2>Choose your date and time slot:</h2>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="row mt-4">
                <div class="col-12 d-flex justify-content-center">
                    <div class="reservation-form-filter">
                        <p class="d-flex flex-column">
                            <label class="text-white">Date:</label>
                            {{ form.date }}
                        <p class="d-flex flex-column">
                            <label class="text-white">Time slot:</label>
                            {{form.duration}}
                        </p>
                        <button type="submit" class="text-white btn btn-dark border rounded border-white">Next</button>
                        <hr class="text-white">
                    </div>
                </div>
            </div>
            
        </form>
    </div>

{% endblock content %}

src/app/back-end/users/templates/users/pages/hammock.html
<svg version="1.0" xmlns="http://www.w3.org/2000/svg"
 width="512.000000pt" height="512.000000pt" viewBox="0 0 512.000000 512.000000"
 preserveAspectRatio="xMidYMid meet">

<g transform="translate(0.000000,512.000000) scale(0.100000,-0.100000)"
fill="{{ fill }}" stroke="none">
<path d="M1150 5015 c-60 -19 -109 -62 -145 -126 l-30 -54 -3 -2255 c-2 -2500
-7 -2315 65 -2399 20 -24 59 -54 87 -67 l51 -24 1385 0 1385 0 51 24 c28 13
67 43 87 67 72 84 67 -101 65 2399 l-3 2255 -30 54 c-36 66 -85 107 -149 126
-72 22 -2747 21 -2816 0z m2671 -188 c47 -23 103 -79 126 -126 16 -33 18 -74
21 -451 2 -369 1 -420 -14 -459 -23 -60 -79 -119 -139 -147 l-50 -24 -1205 0
-1205 0 -50 24 c-60 29 -107 76 -134 136 -20 43 -21 64 -21 451 0 281 4 416
12 440 24 73 88 138 162 166 23 9 333 11 1246 10 1152 -2 1217 -3 1251 -20z
m-85 -1679 c94 -50 143 -131 144 -239 0 -111 -66 -209 -168 -245 -54 -19
-2250 -19 -2304 0 -165 59 -222 269 -112 413 29 39 103 84 153 94 20 4 531 6
1136 5 l1100 -1 51 -27z m0 -705 c54 -29 117 -101 132 -151 39 -128 -16 -262
-133 -325 l-40 -22 -1135 0 -1135 0 -41 22 c-54 29 -117 101 -132 151 -15 50
-15 124 0 174 21 70 100 145 178 169 14 4 529 7 1145 6 l1120 -2 41 -22z m2
-709 c98 -49 146 -134 140 -249 -3 -59 -9 -81 -33 -121 -37 -59 -107 -108
-175 -123 -71 -15 -2149 -15 -2220 0 -68 15 -138 64 -175 123 -24 40 -30 62
-33 121 -6 115 42 200 140 249 l52 26 1126 0 1126 0 52 -26z m-17 -696 c57
-25 115 -83 139 -140 18 -43 22 -65 18 -123 -3 -38 -12 -85 -22 -102 -23 -45
-75 -95 -122 -119 -38 -18 -74 -19 -1163 -22 l-1124 -2 -51 23 c-103 47 -155
127 -156 237 0 97 35 163 123 230 51 38 75 39 1217 37 1004 -2 1108 -4 1141
-19z"/>
<path d="M1373 4665 c-52 -22 -55 -47 -51 -452 l3 -363 28 -27 27 -28 1180 0
1180 0 27 28 28 27 3 370 c3 413 1 428 -60 449 -21 8 -390 11 -1182 11 -959
-1 -1156 -3 -1183 -15z"/>
<path d="M1447 2980 c-49 -39 -42 -116 14 -145 42 -22 2156 -22 2198 0 56 29
63 106 14 145 -25 20 -44 20 -1113 20 -1069 0 -1088 0 -1113 -20z"/>
<path d="M1436 2259 c-14 -17 -26 -41 -26 -54 0 -13 12 -37 26 -54 l26 -31
1097 0 1098 0 21 23 c36 38 38 78 7 115 l-27 32 -1098 0 -1098 0 -26 -31z"/>
<path d="M1459 1575 c-54 -30 -60 -107 -11 -145 25 -20 39 -20 1117 -18 1042
3 1094 4 1113 21 44 40 34 115 -19 142 -42 22 -2160 22 -2200 0z"/>
<path d="M1447 860 c-31 -24 -42 -64 -27 -99 24 -59 -40 -56 1118 -59 723 -1
1076 1 1103 8 71 19 89 105 32 150 -25 20 -39 20 -1113 20 -1069 0 -1088 0
-1113 -20z"/>
<path d="M29 3941 l-29 -29 0 -1001 0 -1000 24 -28 c24 -27 27 -28 143 -31
117 -4 120 -3 151 23 l32 27 0 1009 0 1010 -26 24 c-25 24 -33 25 -146 25
-119 0 -120 0 -149 -29z"/>
<path d="M4796 3945 l-26 -24 0 -1010 0 -1009 32 -27 c31 -26 34 -27 151 -23
116 3 119 4 143 31 l24 28 0 1000 0 1001 -29 29 c-29 29 -30 29 -149 29 -113
0 -121 -1 -146 -25z"/>
<path d="M530 3265 l0 -265 130 0 130 0 0 265 0 265 -130 0 -130 0 0 -265z"/>
<path d="M4330 3265 l0 -265 130 0 130 0 0 265 0 265 -130 0 -130 0 0 -265z"/>
</g>
</svg>

src/app/back-end/users/templates/users/pages/pdf.html
<html>
  <head>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet">
    <link href="{% static 'css/pdf.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="row">
      <div class="col-12 logo-pdf d-flex justify-content-center align-items-center">
        <img src="{% static "imgs/logo.svg" %}" alt="logo_jhoola" class="">
      </div>
    </div>
    <hr>
    <div class="row mb-4">
      <h3 class="mb-3">Reservation details</h3>
      <div class="col-3">
        <p>Reservation ID</p>
        <p>Reserved time</p>
        <p>Date</p>
      </div>
      <div class="col-4">
        <p>{{booking.id}}</p>
        <p>{{booking.get_duration_display}}</p>
        <p>{{ booking.date|date:"l, d/m/Y" }}</p>
      </div>
      <span class="col-5 paid-container d-flex justify-content-center">
        <span class="paid-content">
          Paid
        </span>
      </span>
    </div>

    <div class="row mb-4">
      <h3 class="mb-3">Reserved by</h3>
      <div class="col-6">
        <p>{{ booking.user.fullname}}</p>
        <p>{{ booking.user.user.email}}</p>
      </div>
    </div>

    <div class="row">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Product</th>
            <th scope="col" class="text-end">Amount</th>
          </tr>
        </thead>
        <tbody>
        <tr>
          <td>{{ booking.products.first }} x {{ booking.products.count }}
            <br> Nº
            ({% for product in booking.products.all %}{{ product.id }}{% if not forloop.last %},{% else %}){% endif %}
            {% endfor %}
          </td>
          <td class="text-end">{{ booking.products.first.price }}€</td>
        </tr>
        <tr>
          <th class="text-end col-11">Total price </th>
          <th class="text-end col-1">{{ booking.price }}€</th>
        </tr>
      </tbody>
      </table>     
    </div>
    <div class="qr col-12 d-flex justify-content-start">
      <img src="{{ qr }}" width="100" height="100">
    </div>
    <div class="jhoola-info d-flex justify-content-between align-items-center">
      <div class="me-3">
        <i class="fa-solid fa-phone"></i> +34 922 35 21 21
      </div>
      <div class="me-3">
        <i class="fa fa-envelope"></i> jhoolasl@gmail.com
      </div>
      <div class="me-3">
        <i class="fa-solid fa-globe"></i> www.jhoola.com
      </div>
    </div>

  </body>
</html>