src/app/back-end/booking/urls.py
from django.urls import path

from . import views

app_name = 'booking'
urlpatterns = [
    path('<str:username>/book/', views.booking_view, name='client_book'),
    path('<str:username>/filter/', views.filter_view, name='client_book_filter'),
    path('<str:username>/bookings/', views.booking_list, name='booking_list'),
    path('<str:username>/bookings/<booking_id>/pdf/', views.booking_pdf, name='booking_pdf'),
    path(
        '<str:username>/bookings/<booking_id>/delete', views.delete_booking, name='delete_booking'
    ),
    path('completed/<int:booking_id>/', views.payment_success, name='payment_completed'),
    path('cancelled/<int:booking_id>/', views.payment_cancel, name='payment_cancelled'),
]

src/app/back-end/hotel/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
]

src/app/back-end/jhoola/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from users import views as user_views

from .router import router

urlpatterns = [
    path('login/', user_views.user_login, name='user_login'),
    path('', include('django.contrib.auth.urls')),
    path('', include('hotel.urls')),
    path('', include('users.urls')),
    path('', include('booking.urls')),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/app/back-end/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('manager/bookings/', views.bookings_manager_view, name='manager_bookings'),
    path('manager/products/', views.products_manager_view, name='manager_products'),
    path('manager/', views.manager_dashboard, name='manager_dashboard'),
    path('manager/users/', views.users_manager_view, name='manager_users'),
    path('manager/products/add', views.products_add_manager_view, name='manager_products_add'),
    path('manager/users/add', views.users_add_manager_view, name='manager_users_add'),
    path(
        'manager/users/<username>/edit/', views.users_edit_manager_view, name='manager_users_edit'
    ),
    path(
        'manager/products/<product_id>/edit/',
        views.products_edit_manager_view,
        name='manager_products_edit',
    ),
    path(
        'manager/users/<username>/delete/',
        views.users_delete_manager_view,
        name='manager_users_delete',
    ),
    path(
        'manager/products/<product_id>/delete/',
        views.products_delete_manager_view,
        name='manager_products_delete',
    ),
    path(
        'manager/bookings/<booking_id>/delete/',
        views.bookings_delete_manager_view,
        name='manager_bookings_delete',
    ),
    path(
        'manager/search/<path:query>',
        views.search_manager_view,
        name='manager_search',
    ),
    path(
        'manager/check_reservation/',
        views.check_booking_manager_view,
        name='manager_check_booking',
    ),
]

src/app/back-end/product/models.py
from django.db import models

from hotel.models import Hotel


class FreeManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Product.Status.FREE)


class OccupiedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Product.Status.OCCUPIED)


class Product(models.Model):
    class Status(models.TextChoices):
        FREE = 'FR', 'Free'
        OCCUPIED = 'OC', 'Occupied'

    name = models.CharField(max_length=30, default='Hammock')
    price = models.DecimalField(max_digits=4, decimal_places=2, null=False, default=2.5)
    avatar = models.CharField(max_length=100, blank=True)
    status = models.CharField(max_length=2, choices=Status.choices, default='FR')
    hotel = models.ForeignKey(Hotel, related_name='products', on_delete=models.CASCADE)
    hotel_product_id = models.PositiveIntegerField(editable=False, blank=True, null=True)

    objects = models.Manager()
    free = FreeManager()
    occupied = OccupiedManager()

    class Meta:
        ordering = ['hotel_product_id']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.pk:
            last_product = (
                Product.objects.filter(hotel=self.hotel).order_by('hotel_product_id').last()
            )
            if last_product:
                self.hotel_product_id = last_product.hotel_product_id + 1
            else:
                self.hotel_product_id = 1
        super().save(*args, **kwargs)

src/app/back-end/booking/forms.py
from django import forms
from django.utils import timezone

from product.models import Product

from .models import Booking
from hotel.models import Hotel  


class BookingFilterForm(forms.Form):
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    duration = forms.ChoiceField()

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.fields['duration'].choices = self.get_duration_choices(self.user.hotel)
        self.fields['duration'].initial = Booking.TimeSlots.ALL_DAY

    def clean_date(self):
        date = self.cleaned_data.get('date')
        actual_date = timezone.now().date()
        max_date = actual_date + timezone.timedelta(days=7)

        if actual_date <= date > max_date:
            raise forms.ValidationError('You can only reserve up to one week from today.')
        if date < actual_date:
            raise forms.ValidationError('You cannot reserve for past dates.')
        return date

    def get_duration_choices(self,hotel):
        hotel = Hotel.objects.get(id=hotel.id)
        morning_hours = hotel.opening_morning_hours
        afternoon_hours = hotel.opening_afternoon_hours

        duration_choices = [
            (choice[0], Booking.TimeSlots.get_display_with_hours(choice[0], morning_hours, afternoon_hours)) 
            for choice in Booking.TimeSlots.choices
        ]
        return duration_choices


class BookingForm(forms.ModelForm):
    products = forms.ModelMultipleChoiceField(
        queryset=Product.objects.all(), widget=forms.CheckboxSelectMultiple, required=False
    )

    class Meta:
        model = Booking
        fields = ['products']

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.fields['products'].queryset = Product.objects.filter(hotel=self.user.hotel)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.user = self.user
        if commit:
            instance.save()
        return instance

    def clean_products(self):
        products = self.cleaned_data.get('products')
        user = self.user
        max_products = user.num_guest

        if not products:
            raise forms.ValidationError('You have to choose at least one product')

        if len(products) > max_products:
            raise forms.ValidationError(
                f'You can only reserve a maximum of {max_products} products per time slot.'
            )

        return products

src/app/back-end/booking/api/views.py
from rest_framework import viewsets
from rest_framework.permissions import IsAdminUser

from booking.models import Booking
from users.api.permissions import AdminSiteAccess
from users.models import Client

from .serializers import BookingSerializer


class BookingViewSet(viewsets.ModelViewSet):

    serializer_class = BookingSerializer
    permission_classes = [IsAdminUser | AdminSiteAccess]

    def get_queryset(self):
        bookings = Booking.objects.all()
        if self.request.user.is_staff:
            return bookings
        client = Client.objects.get(user=self.request.user)
        return bookings.filter(user__hotel=client.hotel)

src/app/back-end/booking/views.py
from base64 import b64encode
from datetime import datetime
from io import BytesIO

import weasyprint
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Count
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from qrcode import make

from booking.forms import BookingFilterForm, BookingForm
from product.models import Product
from users.decorators import client_required
from users.models import Client

from .models import Booking
from .tasks import booking_created


@login_required
@client_required
def booking_list(request, username):
    client = get_object_or_404(Client, user=request.user)
    actual_datetime = timezone.now().date()
    bookings = Booking.objects.filter(user=client, date__gte=actual_datetime, paid=True)
    paginator = Paginator(bookings, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(
        request, 'users/pages/bookings.html', {'page_obj': page_obj, 'section': 'My Bookings'}
    )


@client_required
@login_required
def booking_pdf(request, username, booking_id):
    booking = get_object_or_404(Booking, id=booking_id, user__user=request.user)
    selected_hotel = request.session.get('hotel_session_name')
    get_params = f'?booking_id={booking.id}&client_id={request.user.id}&hotel={selected_hotel}'
    path_qr = request.build_absolute_uri(f"{reverse('users:manager_check_booking')}{get_params}")
    qr_rend = BytesIO()
    img = make(path_qr)
    img.save(qr_rend, 'PNG')
    qr_url = f'data:image/png/;base64,{b64encode(qr_rend.getvalue()).decode("ascii")}'
    html = render_to_string('users/pages/pdf.html', {'booking': booking, 'qr': qr_url})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=transaction_{booking_id}.pdf'
    weasyprint.HTML(string=html, base_url=request.build_absolute_uri()).write_pdf(response)
    return response


@login_required
@client_required
def booking_view(request, username):
    date, duration, client, occupied_products, max_products = get_context_data(request, username)
    formatted_date = datetime.strptime(date, '%Y-%m-%d').strftime('%d/%m/%Y')
    formatted_duration = dict(Booking.TimeSlots.choices)[duration]
    if request.method == 'POST':
        form = BookingForm(user=client, data=request.POST)
        if form.is_valid():
            booking = form.save(commit=False)
            products = form.cleaned_data['products']
            if len(products) > max_products:
                messages.error(request, 'You have already reserved all possible hammocks for your account.')
                return redirect('booking:client_book', client)

            if any(
                [
                    product.status
                    for product in products
                    if product.status == Product.Status.OCCUPIED
                ]
            ):
                messages.error(request, 'The selected hammocks are being reserved by another user')
                return redirect('booking:client_book', client)

            total_price = sum(product.price for product in products)
            booking.user = client
            booking.price = total_price
            booking.date = date
            booking.duration = duration
            booking.save()
            form.save_m2m()
            for product in booking.products.all():
                product.status = Product.Status.OCCUPIED
                product.save()
            line_items = [
                {
                    'price_data': {
                        'currency': 'eur',
                        'product_data': {
                            'name': 'Booking',
                        },
                        'unit_amount': int(total_price * 100),
                    },
                    'quantity': 1,
                }
            ]
            metadata = {'booking_id': booking.id}
            success_url = request.build_absolute_uri(
                reverse('booking:payment_completed', kwargs={'booking_id': booking.id})
            )
            cancel_url = request.build_absolute_uri(
                reverse('booking:payment_cancelled', kwargs={'booking_id': booking.id})
            )

            task = booking_created.delay(
                success_url,
                cancel_url,
                metadata,
                line_items,
            )
            url = task.get()
            return redirect(url)
        else:
            for errors in form.errors.values():
                for error in errors:
                    messages.error(request, error)
    else:
        form = BookingForm(user=client)
        products = form.fields['products'].queryset
        for product in products.all():
            product.status = Product.Status.FREE
            product.save()
    return render(
        request,
        'users/pages/book.html',
        {
            'form': form,
            'section': 'Reserve',
            'occupied_products': occupied_products,
            'duration': formatted_duration,
            'date': formatted_date,
        },
    )


@client_required
@login_required
def payment_success(request, booking_id):
    booking = get_object_or_404(Booking, id=booking_id)
    booking.paid = True
    for product in booking.products.all():
        product.status = Product.Status.FREE
        product.save()
    booking.save()

    messages.success(request, 'Your hammocks have been properly reserved')
    return redirect('booking:booking_list', booking.user)


@client_required
@login_required
def payment_cancel(request, booking_id):
    booking = get_object_or_404(Booking, id=booking_id)
    for product in booking.products.all():
        product.status = Product.Status.FREE
        product.save()
    booking.delete()

    messages.error(request, 'There has been an error with your reservation')
    return redirect('booking:booking_list', booking.user)


@login_required
@client_required
def delete_booking(request, username, booking_id):
    client = get_object_or_404(Client, user=request.user)
    booking = get_object_or_404(Booking, id=booking_id, user=client)
    booking.delete()
    messages.success(request, f'Reservation {booking_id} has been succesfully deleted')
    return redirect('booking:booking_list', username=username)


@login_required
@client_required
def filter_view(request, username):
    client = get_object_or_404(Client, user=request.user)
    if request.method == 'POST':
        form = BookingFilterForm(user=client, data=request.POST)
        if form.is_valid():
            request.session['date'] = form.cleaned_data['date'].strftime('%Y-%m-%d')
            request.session['duration'] = form.cleaned_data['duration']
            return redirect('booking:client_book', username=username)
        else:
            for errors in form.errors.values():
                for error in errors:
                    messages.error(request, error)
    else:
        form = BookingFilterForm(user=client)
    return render(request, 'users/pages/filter.html', {'section': 'Reserve', 'form': form})


def get_context_data(request, username):
    date = request.session.get('date')
    duration = request.session.get('duration')
    client = get_object_or_404(Client, user=request.user)
    user_bookings = Booking.objects.filter(date=date, paid=True, user=client)
    total_products = (
        user_bookings.aggregate(total_products=Count('products'))['total_products'] or 0
    )
    max_products = client.num_guest - total_products
    all_date_bookings = Booking.objects.filter(paid=True, date=date)
    occupied_products = []
    match duration:
        case Booking.TimeSlots.AFTERNOON | Booking.TimeSlots.MORNING:
            bookings = all_date_bookings.filter(duration=duration)
            occupied_products.extend(
                [product.id for booking in bookings for product in booking.products.all()]
            )
            all_day_bookings = all_date_bookings.filter(duration=Booking.TimeSlots.ALL_DAY)
            for booking in all_day_bookings:
                occupied_products.extend([product.id for product in booking.products.all()])
        case Booking.TimeSlots.ALL_DAY:
            for booking in all_date_bookings:
                occupied_products.extend([product.id for product in booking.products.all()])

    return (date, duration, client, occupied_products, max_products)

src/app/back-end/product/api/views.py
from rest_framework import viewsets
from rest_framework.permissions import IsAdminUser

from product.models import Product
from users.api.permissions import AdminSiteAccess

from .serializers import ProductSerializer


class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    permission_classes = [IsAdminUser | AdminSiteAccess]

src/app/back-end/users/api/views.py
from rest_framework import viewsets
from rest_framework.permissions import IsAdminUser

from users.models import Client

from .permissions import AdminSiteAccess
from .serializers import ClientSerializer


class ClientViewSet(viewsets.ModelViewSet):
    serializer_class = ClientSerializer
    permission_classes = [IsAdminUser | AdminSiteAccess]

    def get_queryset(self):

        if self.request.user.is_staff:
            return Client.objects.all()
        client = Client.objects.get(user=self.request.user)
        return Client.objects.filter(hotel=client.hotel)

src/app/back-end/users/templates/managers/pages/bookings.html
{% extends "managers/base.html" %}

{% block content%}
<div class="bookings-container">
  <table class="table table-striped table-dark">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Username</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Hammocks</th>
        <th scope="col">Price</th>
        <th scope="col">Duration</th>
        <th scope="col">Date</th>
        <th scope="col">Timestamp</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for booking in page_obj %}
      <tr>
        <th scope="row">{{ booking.id }}</th>
        <td>{{ booking.user }}</td>
        <td>{{ booking.user.fullname }}</td>
        <td>{{ booking.user.user.email }}</td>
        <td>{% for product in booking.products.all %}
              {{ product.id }}{% if not forloop.last %},{% endif %}
            {% endfor %}
        </td>
        <td>{{ booking.price }} €</td>
        <td>{{ booking.get_duration_display }}</td>
        <td>{{ booking.date|date:"d/m/Y" }}</td>
        <td>{{ booking.timestamp|date:"d/m/Y, H:m" }}</td>
        <td>
          <a href="{% url 'users:manager_bookings_delete' booking.id %}" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal{{ booking.id }}">
            <span class="material-icons">
            delete
            </span>
          </a>
        </td>
      </tr>
      {% include "users/messages/delete_booking_modal.html" %}
      {% endfor %}
    </tbody>
  </table>
</div>
  {% include "managers/admin_paginator.html" %}

  {% block domready %}
  {% endblock domready %}
{% endblock %}

src/app/back-end/users/templates/managers/pages/products.html
{% extends "managers/base.html" %}

{% block title %}Products{% endblock title %}

{% load static %}
{% block content %}
<div class="users-container">
  <table class="table table-striped table-dark">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Status</th>
        <th scope="col">Actions</th>
        <th scope="col">
          <a href="{% url 'users:manager_products_add' %}" class="btn btn-success btn-sm flex-row d-flex justify-content-center">
          <span class="material-icons ">
            add_circle_outline
            </span>
        </a>
      </th>
      </tr>
    </thead>
    <tbody>
      {% for product in page_obj %}
      <tr>
        <th scope="row">{{ product.hotel_product_id }}</th>
        <td>{{ product.name }}</td>
        <td>{{ product.price }} €</td>
        <td>{{ product.get_status_display }}</td>
        <td>
          <a href="{% url 'users:manager_products_edit' product.id %}" class="btn btn-warning btn-sm mb-1 mb-lg-0">
            <span class="material-icons">
              edit
              </span>
          </a>
          <a href="{% url 'users:manager_products_delete' product.id %}" class="btn btn-danger btn-sm mb-1 mb-lg-0" data-bs-toggle="modal" data-bs-target="#deleteModal{{ product.id }}">
            <span class="material-icons">
              delete
            </span>
          </a>
        </td>
        <td></td>
      </tr>
      {% include "users/messages/delete_product_modal.html" %}
      {% endfor %}
    </tbody>    
  </table>
</div>
{% include "managers/admin_paginator.html" %}

{% endblock %}

src/app/back-end/users/templates/managers/pages/products_add.html
{% extends "managers/base.html" %}
{% block content %}
<div class="admin-head d-flex flex-row ">
  <a href="javascript:history.back()" class="d-flex align-items-center ps-4 pt-4 pb-0 text-end">
      <span class="material-symbols-outlined m-0 text-end text-white">
          arrow_back
      </span>
  </a>
  <h2 class="font-weight-bolder p-4 pb-0 m-0 text-start text-white">Create products</h2>
</div>

<div class="form-container d-flex justify-content-start col-12 p-4">
  <form action="{% url "users:manager_products_add" %}"  method="post" id="edit-user-form" class="col-10" novalidate>
      {% csrf_token %}
      <div class="form-group d-flex flex-lg-row flex-column mb-4">
          <div class="django-label col-lg-1 col-12 pe-2 pt-2 pt-lg-0">
              Name: 
          </div>
          <div class="django-input pe-4">
              {{ product_add_form.name }}
          </div>
      </div>
      <div class="form-group d-flex flex-lg-row flex-column mb-4">
          <div class="django-label col-1 pe-2">
              Price:
          </div>
          <div class="django-input pe-4">
              {{ product_add_form.price }}
          </div>
      </div>
      <div class="form-group d-flex flex-lg-row flex-column mb-4">
        <div class="django-label col-1 pe-2">
            Quantity:
        </div>
        <div class="django-input pe-4">
            {{ product_add_form.quantity }}
        </div>
    </div>
      <button class="btn btn-block bg-warning justify-content-center" type="submit">Create</button>
  </form>
</div>
{% endblock %}

src/app/back-end/users/templates/managers/pages/search_list.html
{% extends "managers/base.html" %}

{% block title %}Search{% endblock title %}

{% block content %}

{% load model_name %}
<a href="javascript:history.back()" class="d-flex align-items-center ps-4 pt-4 pb-0 text-end">
    <span class="material-symbols-outlined m-0 text-end text-white">
        arrow_back
    </span>
</a>
{% if clients %}
<h2 class="font-weight-bolder pt-0 p-3 m-0 text-center text-white">Clients</h2>
<div class="clients-container">
    <table class="table table-striped table-dark">
    <thead>
        <tr>
            <th scope="col">Username</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Nº Guest</th>
            <th scope="col">Reservations ID</th>
            <th scope="col">Joined</th>
            <th scope="col">Last Login</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
    {% for client in clients %}
        <tr>
            <td>{{ client.user.username }}</td>
            <td>{{ client.user.get_full_name }}</td>
            <td>{{ client.user.email }}</td>
            <td>{{ client.num_guest }}</td>
            <td>{% for booking in client.bookings.all %}
                <a href="{% url 'users:manager_search' booking.id %}">{{ booking.id }}{% if not forloop.last %},{% endif %}</a>
                {% endfor %}
            </td>
            <td>{{ client.user.date_joined|date:"d/m/Y, H:m" }}</td>
            <td>{% if client.user.last_login is None %}
                Not yet logged in
                {% else %}
                {{ client.user.last_login|date:"d/m/Y, H:m" }}
                {% endif %}
            </td>
            <td>
            <a href="{% url 'users:manager_users_edit' client %}" class="btn btn-warning btn-sm mb-1 mb-lg-0">
                <span class="material-icons">
                    edit
                </span>
                </a>
                <a href="{% url "users:manager_users_delete" client %}" class="btn btn-danger btn-sm mb-1 mb-lg-0" data-bs-toggle="modal" data-bs-target="#deleteModal{{ client }}">
                <span class="material-icons">
                    delete
                </span>
                </a>
            </td>
        </tr>
        {% include "users/messages/delete_user_modal.html" %}
        {% endfor %}
    </tbody>
    </table>
</div>
{% endif %}
{% if bookings %}
<h2 class="font-weight-bolder p-3 pt-0 m-0 text-center text-white">Reservations</h2>
<div class="bookings-container">
    <table class="table table-striped table-dark">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Username</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Hammocks ID</th>
        <th scope="col">Price</th>
        <th scope="col">Duration</th>
        <th scope="col">Date</th>
        <th scope="col">Timestamp</th>
        <th scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
    {% for booking in bookings %}
        <tr>
        <th scope="row">{{ booking.id }}</th>
        <td>{{ booking.user }}</td>
        <td>{{ booking.user.fullname }}</td>
        <td>{{ booking.user.user.email }}</td>
        <td>{% for product in booking.products.all %}
                {{ product.id }}{% if not forloop.last %},{% endif %}
            {% endfor %}
        </td>
        <td>{{ booking.price }} €</td>
        <td>{{ booking.get_duration_display }}</td>
        <td>{{ booking.date|date:"d/m/Y" }}</td>
        <td>{{ booking.timestamp|date:"d/m/Y, H:m" }}</td>
        <td>
        <a href="{% url 'users:manager_bookings_delete' booking.id %}" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal{{ booking.id }}">
            <span class="material-icons">
            delete
            </span>
        </a>
        </td>
        </tr>
        {% include "users/messages/delete_booking_modal.html" %}
        {% endfor %}
    </tbody>
    </table>
</div>
{% endif %}

{% if clients|length == 0 and bookings|length == 0 %}
    <h2 class="text-center text-white m-0">No results found</h2>
{% endif %}

{% include "managers/admin_paginator.html" %}
{% endblock %}

src/app/back-end/users/templates/managers/pages/users.html
{% extends "managers/base.html" %}
{% load static %}

{% block content %}
<div class="users-container">
    <table class="table table-striped table-dark">
      <thead>
        <tr>
          <th scope="col">Username</th>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Nº Guest</th>
          <th scope="col">Reservations ID</th>
          <th scope="col">Joined</th>
          <th scope="col">Last Login</th>
          <th scope="col">Actions</th>
          <th scope="col">
            <a href="{% url 'users:manager_users_add' %}" class="btn btn-success btn-sm flex-row d-flex justify-content-center">
            <span class="material-icons ">
              add_circle_outline
              </span>
          </a>
        </th>
        </tr>
      </thead>
      <tbody>
        {% for client in page_obj %}
        <tr>
          <td>{{ client.user }}</td>
          <td>{{ client.fullname }}</td>
          <td>{{ client.user.email }}</td>
          <td>{{ client.num_guest }}</td>
            <td>{% for booking in client.bookings.all %}
              <a href="{% url 'users:manager_search' booking.id %}">{{ booking.id }}{% if not forloop.last %},{% endif %}</a>
              {% endfor %}
            </td>
            <td>{{ client.user.date_joined|date:"d/m/Y, H:i" }}</td>
            <td>{% if client.user.last_login is None %}
                Not yet logged in
                {% else %}
                {{ client.user.last_login|date:"d/m/Y, H:i" }}
                {% endif %}
            </td>
          <td>
            <a href="{% url 'users:manager_users_edit' client %}" class="btn btn-warning btn-sm mb-1">
              <span class="material-icons">
                edit
                </span>
            </a>
            <a href="{% url "users:manager_users_delete" client %}" class="btn btn-danger btn-sm mb-1" data-bs-toggle="modal" data-bs-target="#deleteModal{{ client }}">
              <span class="material-icons">
                delete
              </span>
            </a>
          </td>
          <td></td>
        </tr>
        {% include "users/messages/delete_user_modal.html" %}
        {% endfor %}
      </tbody>    
    </table>
</div>

{% include "managers/admin_paginator.html" %}

{% endblock %}

src/app/back-end/users/templates/managers/pages/users_add.html
{% extends "managers/base.html" %}
{% block content %}
<div class="admin-head d-flex flex-row ">
    <a href="{% url "users:manager_users" %}" class="d-flex align-items-center ps-4 pt-4 pb-0 text-end">
        <span class="material-symbols-outlined m-0 text-end text-white">
            arrow_back
        </span>
    </a>
    <h2 class="font-weight-bolder p-4 pb-0 m-0 text-start text-white">Create new client</h2>
</div>

<div class="form-container d-flex justify-content-start col-12 p-4">
    <form action="{% url 'users:manager_users_add' %}" method="post" id="create-user-form" class="col-10">
        {% csrf_token %}
        <div class="form-group d-flex flex-lg-row flex-column mb-4">
            <div class="django-label col-lg-1 col-12 pe-2 pt-2 pt-lg-0">
                {{ user_form.username.label_tag }} 
            </div>
            <div class="django-input pe-4">
                {{ user_form.username }}
            </div>
            <div class="django-label col-lg-1 col-12 pe-2 pt-2 pt-lg-0">
                {{ user_form.first_name.label_tag }} 
            </div>
            <div class="django-input pe-4">
                {{ user_form.first_name }}
            </div>
            <div class="django-label col-lg-1 col-12 pe-2 pt-2 pt-lg-0">
                {{ user_form.last_name.label_tag }} 
            </div>
            <div class="django-input pe-4">
                {{ user_form.last_name }}
            </div>
        </div>
        <div class="form-group d-flex flex-lg-row flex-column mb-4">
            <div class="django-label col-1 pe-2">
                Email:
            </div>
            <div class="django-input pe-4">
                {{ user_form.email }}
            </div>
            <div class="django-label col-lg-1 col-12 pe-2 pt-2 pt-lg-0">
                {{ user_form.num_guest.label_tag }} 
            </div>
            <div class="django-input pe-4">
                {{ user_form.num_guest }}
            </div>
                {{ user_form.password }}
                {{ user_form.hotel }}
        </div>
        <button class="btn btn-block bg-warning justify-content-center" type="submit">Create client</button>
    </form>
</div>
{% endblock %}